import React, {useEffect, useState} from "react";
import {createRoot} from "react-dom/client";
import "./style.css";

const route = () => window.location.pathname.match(/^\/data(?:\/([a-z0-9-]+))?\/?/);
const api = "/data/api";
const enc = value => value.split("/").map(encodeURIComponent).join("/");
const bytes = value => `${(value / 1073741824).toFixed(1)} GiB`;
const Spinner = ({label = "Loading"}) => <div className="loading"><i />{label}…</div>;

function Overview({data}) { const s = data.storage, status = s.free_percent < 10 || s.free_bytes < 50e9 ? "danger" : s.free_percent < 20 || s.free_bytes < 100e9 ? "warn" : "ok"; return <main><header className="topbar"><b>TESTBENCH DATA</b><span>READ-ONLY PORTAL</span></header><section className="storage card"><div><div className="label">SERVER STORAGE</div><strong>{bytes(s.free_bytes)} free</strong><small>{s.free_percent}% free · {bytes(s.used_bytes)} used of {bytes(s.total_bytes)}</small></div><span className={`pill ${status}`}>{status.toUpperCase()}</span></section><h2>Machines</h2><div className="machine-grid">{data.machines.map(m => <a className="machine-card" href={`/data/${m.machine}/`} key={m.machine}><div className="machine-icon">▣</div><div><h3>{m.machine}</h3><p>{m.session_count} sessions · {m.latest_session?.status || "no data"}</p><small>{m.latest_session?.started_at_utc || "No sessions yet"}</small></div><span>VIEW DATA →</span></a>)}</div></main>; }

function makeTree(files) { const root = {}; files.forEach(file => { let node = root; const pieces = file.path.split("/"); pieces.forEach((piece, index) => { if (index === pieces.length - 1) node[piece] = file; else node = node[piece] ||= {}; }); }); return root; }
function Tree({node, select, chosen, prefix = ""}) { return <ul>{Object.entries(node).map(([name, value]) => value.path ? <li key={value.path}><button className={`file-node ${chosen?.path === value.path ? "selected" : ""}`} onClick={() => select(value)}>▤ {name}</button></li> : <li key={`${prefix}/${name}`}><details open><summary>▸ {name}</summary><Tree node={value} select={select} chosen={chosen} prefix={`${prefix}/${name}`} /></details></li>)}</ul>; }

function CsvViewer({preview, loadPage}) { if (!preview) return <Spinner label="Loading CSV"/>; return <><div className="file-heading"><div><div className="label">CSV PREVIEW</div><h2>{preview.path.split("/").at(-1)}</h2><small>Rows {preview.offset + 1}–{preview.offset + preview.rows.length} · 250 rows per page</small></div><div><button disabled={!preview.offset} onClick={() => loadPage(Math.max(0, preview.offset - preview.limit))}>← PREVIOUS</button><button disabled={!preview.has_more} onClick={() => loadPage(preview.offset + preview.limit)}>NEXT →</button></div></div><div className="csv-scroll"><table className="csv"><thead><tr><th>#</th>{preview.columns.map(c => <th key={c}>{c}</th>)}</tr></thead><tbody>{preview.rows.map((row, index) => <tr key={preview.offset + index}><td>{preview.offset + index + 1}</td>{preview.columns.map((_, col) => <td key={col}>{row[col] ?? ""}</td>)}</tr>)}</tbody></table></div></>; }

function Machine({machine}) {
  const [sessions, setSessions] = useState([]), [session, setSession] = useState(null), [files, setFiles] = useState([]), [file, setFile] = useState(null), [preview, setPreview] = useState(null), [loading, setLoading] = useState(true), [fileLoading, setFileLoading] = useState(false), [dark, setDark] = useState(localStorage.theme !== "light");
  useEffect(() => { document.documentElement.classList.toggle("light", !dark); localStorage.theme = dark ? "dark" : "light"; }, [dark]);
  useEffect(() => { setLoading(true); fetch(`${api}/machines/${machine}/sessions`).then(r => r.json()).then(setSessions).finally(() => setLoading(false)); }, [machine]);
  const openSession = async item => { setSession(item); setFiles([]); setFile(null); setPreview(null); setFileLoading(true); try { setFiles(await fetch(`${api}/machines/${machine}/sessions/${encodeURIComponent(item.session_id)}/artifacts`).then(r => r.json())); } finally { setFileLoading(false); } };
  const loadPreview = async (selected, offset = 0) => { if (!selected.path.endsWith(".csv")) return; setFileLoading(true); try { setPreview(await fetch(`${api}/machines/${machine}/sessions/${encodeURIComponent(session.session_id)}/csv-preview/${enc(selected.path)}?offset=${offset}`).then(r => r.json())); } finally { setFileLoading(false); } };
  const selectFile = selected => { setFile(selected); setPreview(null); loadPreview(selected); };
  const back = () => { setSession(null); setFiles([]); setFile(null); setPreview(null); };
  return <main><header className="topbar"><a href="/data/">← MACHINES</a><b>{machine.toUpperCase()}</b><button onClick={() => setDark(!dark)}>{dark ? "LIGHT" : "DARK"}</button></header>{!session && <section className="card"><div className="file-heading"><div><div className="label">ACQUISITION SESSIONS</div><h2>Tests</h2></div></div>{loading ? <Spinner/> : <table><thead><tr><th>Started</th><th>Name</th><th>Status</th><th>Runs</th><th /></tr></thead><tbody>{sessions.map(item => <tr key={item.session_id}><td>{item.started_at_utc}</td><td>{item.name || item.session_id}</td><td><span className={`pill ${item.status === "success" ? "ok" : "warn"}`}>{item.status}</span></td><td>{item.run_count}</td><td><button onClick={() => openSession(item)}>OPEN →</button><a href={`${api}/machines/${machine}/sessions/${encodeURIComponent(item.session_id)}/download`}>ZIP</a></td></tr>)}</tbody></table>}</section>}{session && <section className="explorer"><aside><button className="back" onClick={back}>← ALL TESTS</button><div className="label">{session.name || session.session_id}</div>{fileLoading && !files.length ? <Spinner/> : <Tree node={makeTree(files)} select={selectFile} chosen={file}/>}</aside><article>{!file && <div className="empty"><div className="machine-icon">▤</div><h2>Select a file</h2><p>Choose a CSV file in the tree to inspect its contents.</p></div>}{file && fileLoading && <Spinner label="Loading file"/>}{file && !fileLoading && file.path.endsWith(".csv") && <CsvViewer preview={preview} loadPage={offset => loadPreview(file, offset)}/>} {file && !fileLoading && !file.path.endsWith(".csv") && <div className="empty"><h2>{file.path.split("/").at(-1)}</h2><p>This file type is not previewed in the portal.</p><a href={`${api}/machines/${machine}/sessions/${encodeURIComponent(session.session_id)}/artifacts/${enc(file.path)}`}>DOWNLOAD FILE</a></div>}</article></section>}</main>;
}

function App() { const machine = route()?.[1] || null, [overview, setOverview] = useState(null); useEffect(() => { if (!machine) fetch(`${api}/overview`).then(r => r.json()).then(setOverview); }, [machine]); return machine ? <Machine machine={machine}/> : overview ? <Overview data={overview}/> : <main><Spinner/></main>; }
createRoot(document.getElementById("root")).render(<App/>);
